//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int Id { get; set; }
        public int Id_worker { get; set; }
        public int Id_request { get; set; }
        public int Credit_sum { get; set; }
        public System.DateTime Date_of_issue { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
